services:
  hermes:
    image: nousresearch/hermes-agent:latest
    container_name: hermes
    restart: unless-stopped
    command: gateway run
    ports:
      - "8642:8642" # API
      - "8644:8644" # Webhook
    volumes:
      - hermes:/opt/data
      - ./hermes/SOUL.md:/opt/data/SOUL.md
      - ./hermes/AGENTS.md:/opt/data/AGENTS.md
      - ./hermes/config.yaml:/opt/data/config.yaml
      - ./hermes/workspace:/workspace:rw
      - ./hermes/memories:/opt/data/memories:rw
    environment:
      - API_SERVER_ENABLED=true
      - API_SERVER_HOST=0.0.0.0
    env_file:
      - .env

volumes:
  hermes:
